# trying setting up for nginx

version: '3.8'

services:
  
  nginx:
    build: ./requirements/nginx
    container_name: nginx #container_name == image ???????
    # image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '443:443'
    volumes:
      - ../secrets:/etc/letsencrypt
      #mounts cert and ket directly into the container
      # - ./data:/data 
      # for saving certificates?
    networks:
      - my_network

  #just blueprint for the mariadb
  mariadb:
    build: ./requirements/mariadb
    container_name:  mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - my_network

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    #brauche ich ein depends on?
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - my_network
    
volumes:
  db_data:
  wp_data:

networks:
  my_network:
    driver: bridge
  # worpress_data:/var/www/html:ro./nginx/ssl:/etc/ssl/:ro ???? research!